global using System;
global using System.Buffers.Binary;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.IO;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading.Tasks;
global using System.Xml;
global using System.Xml.Serialization;

global using Object = MikuMikuLibrary.Objects.Object;